"""RTM 결과를 프론트엔드(`frontend/`)가 읽는 JS 파일로 내보낸다.

`app.js`의 문서 비교 화면은 `window.DOCREVIEW.compare`만 읽으므로,
그 객체 하나만 실제 결과로 교체하면 서버 없이 실데이터가 렌더된다.
나머지 화면(단일 검토·체크리스트 등)은 기존 목업을 그대로 쓴다.
"""
from __future__ import annotations

import json
from pathlib import Path

from modules.shared import Document, Finding, RtmRow

from .stages import review_stages

# app.js는 이 세 가지 type만 안다 (D.typeMeta).
_DOC_TO_TYPE = {"parent": "missing", "child": "extra"}

_BANNER = "// GENERATED by `docsuree compare --emit-ui`. 직접 수정하지 마세요.\n"


def _finding_to_ui(f: Finding, index: int) -> dict:
    """엔진 Finding → app.js가 기대하는 compare finding 모양."""
    kind = _DOC_TO_TYPE.get(f.document or "", "mismatch")
    section = f.anchor.section
    # a=상위문서 위치, b=하위문서 위치. 지적사항이 가리키는 쪽에만 채운다.
    # mismatch의 anchor는 하위문서(설계) 섹션이다 — 고칠 곳이 거기다.
    a = section if kind == "missing" else None
    b = section if kind in ("extra", "mismatch") else None
    return {
        "id": f"c{index}",
        "type": kind,
        "sev": f.severity.value,
        "a": a,
        "b": b,
        "message": f.message,
        "suggestion": f.suggestion or "",
    }


def _stats(rows: list[RtmRow], ui_findings: list[dict]) -> dict:
    linked = sum(1 for r in rows if r.status == "linked")
    missing = sum(1 for r in rows if r.status == "missing")
    orphan = sum(1 for r in rows if r.status == "orphan")
    out_of_scope = sum(1 for r in rows if r.status == "out_of_scope")
    rolled_up = sum(1 for r in rows if r.status == "rolled_up")
    return {
        # 검사 대상 요건 = 연결된 것 + 누락된 것 + 접힌 것
        # (범위 밖은 하위문서 책임이 아니라 뺀다)
        "requirements": linked + missing + rolled_up,
        # 조용히 빼지 않는다. 화면에 개수를 띄워 사용자가 범위를 확인하게 한다.
        "out_of_scope": out_of_scope,
        # 부모 수준에서만 검증된 세부 요건. 누락은 아니지만 연결과도 다르다 —
        # 개별 검증 여부는 사람이 봐야 하므로 따로 센다.
        "rolled_up": rolled_up,
        "matched": linked,
        "missing": missing,
        # 내용 대조(triage) 결과. LLM이 없으면 0건이다.
        # sev=info는 "LLM 판정 실패"(=모르는 상태) 표시라 불일치로 세지 않는다.
        # 목록에는 그대로 보이므로 사용자가 검토 구멍을 알아챌 수 있다.
        "mismatch": sum(1 for f in ui_findings
                        if f["type"] == "mismatch" and f["sev"] != "info"),
        "extra": orphan,
    }


def _stages(parent: Path, child: Path, stats: dict, n_findings: int) -> list[dict]:
    return [
        {"label": "Ingestion", "desc": "상위·하위 문서 적재",
         "detail": f"{parent.name} · {child.name}"},
        {"label": "Alignment", "desc": "요구 ID 매칭",
         "detail": f"{stats['requirements']} requirements"},
        {"label": "Cross-check", "desc": "누락·근거없음 검사",
         "detail": "traceability checker"},
        {"label": "Report", "desc": "중복 제거 · 정렬",
         "detail": f"{n_findings} findings"},
    ]


def to_ui_payload(
    rows: list[RtmRow],
    findings: list[Finding],
    parent_path: str | Path,
    child_path: str | Path,
) -> dict:
    """`window.DOCREVIEW.compare`에 그대로 대입할 수 있는 dict를 만든다."""
    parent, child = Path(parent_path), Path(child_path)
    ui_findings = [_finding_to_ui(f, i + 1) for i, f in enumerate(findings)]
    stats = _stats(rows, ui_findings)
    return {
        "docA": {"name": parent.name, "type": parent.suffix.lstrip(".").upper()},
        "docB": {"name": child.name, "type": child.suffix.lstrip(".").upper()},
        "stats": stats,
        "stages": _stages(parent, child, stats, len(ui_findings)),
        "findings": ui_findings,
    }


def _review_finding_to_ui(f: Finding, index: int) -> dict:
    return {
        "id": f"f{index}",
        "checker": f.checker,
        # 무엇이 잡았나 — 화면 뱃지가 쓴다. checker 는 관점 묶음이라
        # 일곱 검사기가 한 이름을 나눠 쓴다(shared/models.py Finding.label).
        "label": f.label,
        # 무엇이 잘못됐나(모순·표기·모호). label 이 "무엇이 잡았나"라면 이건 종류다.
        # 없으면 화면이 label 로 되돌아간다 — 규칙 검사기는 아직 안 채운다.
        "kind": f.kind,
        # "문제를 찾았다"가 아니라 "검사를 못 했다"는 보고. 지금까지 payload 에
        # 안 실려서, 이력을 다시 읽는 쪽(반영 확인)이 지적과 구별할 수 없었다.
        "unreviewed": f.unreviewed,
        # 재질의 왕복 끝에 근거를 다시 찾은 지적(rescue). 화면이 출처 뱃지를 단다.
        "rescued": f.rescued,
        # 재확인 여정(처음 인용·검색어). 화면이 "어떻게 다시 찾았나"를 그린다.
        "rescue_trace": f.rescue_trace,
        "sev": f.severity.value,
        "message": f.message,
        "section": f.anchor.section,
        "page": f.anchor.page,
        # 미리보기가 하이라이트할 원문 인용. verify_quotes가 "이 인용은 원문에
        # (공백 정규화 후) 축자적으로 존재한다"를 이미 보증했으므로, 화면은 찾기만
        # 하면 된다. 규칙기반 체커는 근거를 달지 않아 빈 배열이다 — 그 경우 화면은
        # 절로 스크롤만 한다.
        "evidence": [
            # image_no 가 있으면 그 근거는 그림 설명에서 나왔다는 뜻이다. 뷰어는
            # 그것으로 형광펜을 그림 자체에 얹는다 — 그림 설명은 PDF 텍스트
            # 레이어에 없어서 인용문으로는 위치를 찾을 수 없다.
            # source 가 있으면 그 근거는 **본문 밖**에서 나왔다(머릿말·꼬리말).
            # 뷰어는 본문에서 찾지 않는다 — 찾으면 우연히 맞는 곳을 짚는다.
            {"quote": e.quote, "section": e.anchor.section, "page": e.anchor.page,
             "image_no": e.image_no, "source": e.source}
            for e in f.evidence
        ],
        "suggestion": f.suggestion or "",
    }


def _sections_to_ui(document: Document | None) -> list[dict]:
    """정규화된 절 → 미리보기가 렌더할 본문.

    text를 가공하지 않는다. 추출기가 낸 모양(`### 제목`, `| 셀 | 셀 |`)을 그대로
    넘기고 렌더는 화면이 한다 — 여기서 HTML을 만들면 CLI(--emit-ui)와 웹이 서로
    다른 것을 보게 된다.
    """
    if document is None:
        return []
    return [
        {
            "id": s.id,
            "title": s.title,
            "level": s.level,
            "page": s.anchor.page,
            "text": s.text,
        }
        for s in document.iter_sections()
    ]


def to_ui_review_payload(
    findings: list[Finding],
    source_path: str | Path,
    *,
    images: list[dict] | None = None,
    sections: int = 0,
    chunks: int = 0,
    chars: int = 0,
    document: Document | None = None,
) -> dict:
    """단일 검토 결과 → app.js가 읽는 doc/sections/findings/stages.

    `sections`(int)는 진행 화면이 쓰는 개수이고, 출력의 `sections`(list)는 미리보기가
    쓰는 본문이다. 이름이 겹치지만 하나는 입력 통계, 하나는 출력 데이터다.

    document를 안 주면 본문 없이(빈 리스트) 나간다 — 이 기능 이전의 이력이 그렇다.
    화면은 그 경우 "본문이 저장되지 않았습니다"를 띄운다.
    """
    path = Path(source_path)
    ui_findings = [_review_finding_to_ui(f, i + 1) for i, f in enumerate(findings)]
    return {
        "doc": {"name": path.name, "type": path.suffix.lstrip(".").upper()},
        "sections": _sections_to_ui(document),
        "findings": ui_findings,
        # 그림의 번호와 **원본 크기**. 뷰어가 /api/locate 에 그대로 돌려보내면
        # 서버가 뷰어용 PDF 안의 이미지와 짝지어 좌표를 낸다(annotate_pdf.
        # match_images). 크기가 열쇠다 — 개수가 어긋나는 문서가 있어 순서만으로는
        # 못 짝짓는다. part 나 설명은 보내지 않는다(화면이 쓰지 않는다).
        "images": [{"no": im["no"], "width": im.get("width") or 0,
                    "height": im.get("height") or 0}
                   for im in (images or [])],
        "stages": review_stages(chars, sections, chunks, len(ui_findings)),
    }


def to_ui_criteria_review_payload(result, source_path, *, as_checklist=False) -> dict:
    """기준 인식 검토 → 화면용. 기준↔지적 연결과 평면 findings를 함께 낸다.

    평면 findings 는 기존 단일 검토 렌더가 그대로 읽는다(이력 재열기 포함).
    항목별 그룹은 그 **같은** 지적 dict 를 참조한다 — 번호가 갈리지 않게.

    일반 단일 검토도 ``criteriaResults``를 받는다. 업로드 기준을 고른 경우에만
    기존 그룹 화면을 여는 ``checklist`` 별칭도 함께 싣는다. 따라서 업로드 여부는
    표시 방식을 바꿀 뿐, 실행 엔진이나 추적성 계약을 바꾸지 않는다.
    """
    base = to_ui_review_payload(
        result.findings, source_path,
        images=getattr(result, "images", None),
        sections=result.section_count, chunks=result.chunk_count,
        chars=result.char_count, document=result.document)
    # result.findings 와 base["findings"] 는 같은 순서다(to_ui_review_payload 가
    # 순서대로 번호를 매긴다). 객체 id 로 이어, 항목별 findings 가 같은 dict 를 쓴다.
    ui_by_id = {id(f): uf for f, uf in zip(result.findings, base["findings"])}
    # note·mode 도 싣는다. 화면이 "이 기준이 뭐였는지"를 보여주려면 본문만으론
    # 모자란다 — 공통 기준 본문은 "아래 양식으로"에서 끊겨 있고(세부는 note 에
    # 있다), "왜 사람 확인 필요인가"의 답은 mode 다. 원본 엑셀은 사내 파일이라
    # 앱에 없어서, 검토자가 다른 데서 확인할 길이 없다.
    items = [{"no": it.no, "text": it.text, "group": it.group, "status": it.status,
              "note": getattr(it, "note", "") or "",
              "mode": getattr(it, "mode", "") or "",
              # 그 mode 를 기준이 직접 적었는지. 화면이 "판정할 수 없다"(사람이
              # 그렇게 정했다)와 "아직 검사기가 없다"(아무도 안 정했다)를 가른다.
              "mode_declared": bool(getattr(it, "mode_declared", False)),
              # 공통·팀은 늘 돌지만 업로드는 검토자가 고른 층이다 — 출처를 화면이 말한다.
              "layer": getattr(it, "layer", "") or "",
              "findings": [ui_by_id[id(f)] for f in it.findings]}
             for it in result.items]
    summary = {"flagged": sum(1 for it in result.items if it.status == "flagged"),
               "clean": sum(1 for it in result.items if it.status == "clean"),
               # 검사기가 붙었지만 LLM 이 답하지 않아 판정을 못 낸 항목. clean 에
               # 섞으면 "이상 없음"으로, flagged 에 섞으면 "문제 발견"으로 잘못 읽힌다.
               "unreviewed": sum(1 for it in result.items if it.status == "unreviewed"),
               # 이 기준이 **이 문서를 대상으로 하지 않는다**. 고칠 것이 없으므로
               # unreviewed(고쳐야 할 것)와 갈라 센다. 안 가르면 "검사 안 됨" 이
               # 부풀어 검토자가 장비·설정을 뒤지게 된다.
               "na": sum(1 for it in result.items if it.status == "na"),
               # 애초에 문서 검토 항목이 아닌 것(생성 기능·이력 관리).
               "outofscope": sum(1 for it in result.items
                                 if it.status == "outofscope"),
               # LLM 이 아예 답하지 않은 항목. unreviewed(응답은 왔는데 이 기준
               # 판정만 빠짐)와 갈라 센다 — 앞은 서버를 고쳐야 하고 뒤는 다시
               # 돌리면 나올 수 있다.
               "noanswer": sum(1 for it in result.items
                               if it.status == "noanswer"),
               "manual": sum(1 for it in result.items if it.status == "manual"),
               "total": len(result.items)}
    criteria_results = {"items": items, "summary": summary}
    base["criteriaResults"] = criteria_results
    if as_checklist:
        base["checklist"] = criteria_results
    return base


def to_ui_checklist_review_payload(result, source_path) -> dict:
    """구 API 호환: 업로드 체크리스트 그룹 화면까지 켜는 payload."""
    return to_ui_criteria_review_payload(result, source_path, as_checklist=True)


def _js_literal(payload: dict) -> str:
    # "</script>"가 문자열에 섞여 태그를 조기 종료하는 것을 막는다.
    return json.dumps(payload, ensure_ascii=False, indent=2).replace("<", "\\u003c")


def render_ui_js(payload: dict) -> str:
    """페이지가 <script>로 읽는 JS. docreview-data.js 뒤에 로드되어 compare만 덮어쓴다."""
    return (
        f"{_BANNER}"
        "(function () {\n"
        "  if (!window.DOCREVIEW) return;\n"
        f"  window.DOCREVIEW.compare = {_js_literal(payload)};\n"
        "})();\n"
    )


def render_review_ui_js(payload: dict) -> str:
    """단일 검토 결과를 doc/sections/findings/stages에 덮어쓰는 JS."""
    return (
        f"{_BANNER}"
        "(function () {\n"
        "  if (!window.DOCREVIEW) return;\n"
        f"  var r = {_js_literal(payload)};\n"
        "  window.DOCREVIEW.doc = r.doc;\n"
        # 미리보기 본문. 이 줄이 없으면 --emit-ui로 만든 결과에서만 미리보기가
        # 비어 보인다 — 웹(SSE)은 payload를 통째로 쓰므로 증상이 안 나타난다.
        "  window.DOCREVIEW.sections = r.sections;\n"
        "  window.DOCREVIEW.findings = r.findings;\n"
        "  window.DOCREVIEW.stages = r.stages;\n"
        "  window.DOCREVIEW.criteriaResults = r.criteriaResults || null;\n"
        "  window.DOCREVIEW.checklist = r.checklist || null;\n"
        "})();\n"
    )
